name: "CD Pipeline"

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "hungtran679/volunteerwork-frontend"
  IMAGE_TAG: "${{ github.sha.substr(0,8) }}-${{ github.run_number }}"

  ECS_CLUSTER: "volunteerwork-prod-ecs-cluster"
  ECS_TASK_DEFINITION_FAMILY: "volunteerwork-prod-frontend-family"
  ECS_SERVICE: "volunteerwork-prod-frontend-service"
  ECS_CONTAINER_NAME: "frontend"

  AWS_REGION: "us-east-1"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
      
      - name: Push to Docker Registry
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:   
    runs-on: ubuntu-latest
    needs: build_and_publish
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION_FAMILY }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.ECS_CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE}}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

