name: CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up NodeJS runtime
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Test
        run: npm run test